discord:
  - id: "epicgames"
    discord_channel: "epicgames"
    discord_username: "epicgames-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/910312047751876628/vx3emyH4TxN7JPS04z5mJHEzognFXoT1QlPy3YcQnEVaO6YfA6crJKn3F6MUpDpGDMqi"
  - id: "rcopstein"
    discord_channel: "rcopstein"
    discord_username: "rcopstein-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/912113126680432701/BAmUWrhyQYTYHfDWV-rB9wb-OEMjDPGGdXmm955HTYFOS9AM19veLixXi8kuT7-7kRJu"
  - id: "clubhouse"
    discord_channel: "clubhouse"
    discord_username: "clubhouse-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/912134070660636672/NpwUXXS1W3ceAHwUEmRlRl8tBjUpqSoix9K_OCIa1K6V94vhWDlGzWcrWjMdu6wpER1M"
  - id: "takeovers"
    discord_channel: "takeovers"
    discord_username: "takeovers-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/935002886209962094/vAqDIsRW_2hIHaTd3OfMx7Wv7C5Y-Cw4NbmZZqi2Jy3K4Un3BdjPhaVBhzpAF4R5HMGw"
  - id: "cloud-buckets"
    discord_channel: "cloud-buckets"
    discord_username: "cloud-buckets-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/935738775424868513/IohDz3NG6BIlZjjf09_E6MLh5hSMUD7ZdlKeUyvQPUHRTTl9Yrp7IfXDOAJOXBuHVKVT"
  - id: "dalfox"
    discord_channel: "dalfox"
    discord_username: "dalfox-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/936385714428469348/600PK3Jpg-f5IkBkrzvoLb03EY-MSRHIwmSABmuZjzOj4b0bxztQFXqCqbKi2Ls8CZvV"
  - id: "project-sonar-s3"
    discord_channel: "project-sonar-s3"
    discord_username: "project-sonar-s3-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/937190363964264489/ZwGYWxdztt_uuBoNDsKy2Mprn5dp_vv6CXVfLb0eMONBWDxdSiWQYAapWwoxJcctnxYf"
  - id: "interactsh"
    discord_channel: "interactsh"
    discord_username: "interactsh-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/939033874531496017/yVWRTd554UGDuROx5TQXj63wVL_bDTbEIb299YlG__Nz2vGofuXJN4PwQ0tbMJkzzrmf"
  - id: "interactsh-log4shell"
    discord_channel: "interactsh-log4shell"
    discord_username: "interactsh-log4shell-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/980263609122848828/K6L7gn4RE3S5MgLHkjN1waKJb3jDtnUZBBC8sSnOEXGfWrjCOoH4Ipz6rriYylOn0GNU"
  - id: "interactsh-ssrf"
    discord_channel: "interactsh-ssrf"
    discord_username: "interactsh-ssrf-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/980264089542615042/1-DDvr3WwrU4yodyZD7wWa13X97DaP0e62TYxUwFGwIaxq2YxcJ9nZfGZ4Pn2nrsEjqo"
  - id: "interactsh-rfi"
    discord_channel: "interactsh-rfi"
    discord_username: "interactsh-rfi-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/980579533499555870/ThZCpfhXfb6sSgaNnJmMYx31Vk44cUfBraEmjYFzYJHOwOVponMIv675-I6zJpNYMvtI"
  - id: "interactsh-xxe"
    discord_channel: "interactsh-xxe"
    discord_username: "interactsh-xxe-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/980582374414897243/TQtFAD_-qhgmK28Eqb6Dw4hxge6MG-qckqq9d2F5mpbup4Wyo_7F4LslijM5VF6u-B_e"
  - id: "sqlmap"
    discord_channel: "sqlmap"
    discord_username: "sqlmap-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/940026389304840222/lRioLnCZOl5hQQ5DTJYMK3X8bmDhGj-HEDuznPoDb6NDIKgMdsEpw5lFAWQUdN0yCujc"
  - id: "root-domains"
    discord_channel: "root-domains"
    discord_username: "root-domains-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/944081978314063912/Bj7aJKnQDjB8skeryrdgl1sEbYtn7Hv4xC1w7D1M4VQ_74o8tutaB4i4z-xKnIpkg923"
  - id: "sub-domains"
    discord_channel: "sub-domains"
    discord_username: "sub-domains-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/945005423717658694/70qgG3q-H7ISlfYJsK1Rh8YShkAPhV_M225qi0RY1tfv2VQ4C8rauUGXl_CG84jxNfro"
  - id: "epam-bbp"
    discord_channel: "epam-bbp"
    discord_username: "epam-bbp-bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/985381806704574544/2tnGqWqdTz0ou5S1DN1TZg1iOHtOMGyMF7p9bv5TvDVkBOEQwvIhCqy3VqIutKhs7MsV"
